name: 'user_srv'
mysql:
  host: '110.40.150.61'
  port: 3306
  name: 'shop_user_srv'
  user: 'root'
  password: 'fshing'
consul:
  host: '110.40.150.61'
  port: 8500

# nacos
host: '192.168.0.104'
port: 8849
namespace: '6af9810f-2e08-4e9e-ab52-ae2868fe5fcc'
user: 'nacos'
password: 'nacos'
dataid: 'user-srv.json'
group: 'dev'